// Writes docs/exercise-ids.md from apps/api/resources/content/exercises.json and the take-home tracks.
// Run after any change to the exercises: bun scripts/exercise-ids.ts
// (tests/docs.test.ts fails while the doc is out of date).
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
export const DOC = join(root, 'docs/exercise-ids.md')

type Exercise = { id: string; title: string; minutes: number }
type Track = { id: string; title: string; published: boolean }

const content = (path: string) => JSON.parse(readFileSync(join(root, 'apps/api/resources/content', path), 'utf8'))
const table = (exercises: Exercise[]) =>
  [
    '| # | Id | Title | Minutes | Live page, focused on it |',
    '|---|---|---|---|---|',
    ...exercises.map((e, i) => `| ${i + 1} | \`${e.id}\` | ${e.title.replace(/\|/g, '\\|')} | ${e.minutes} | \`/live?embed&exercise=${e.id}\` |`),
  ].join('\n')
const sum = (exercises: Exercise[]) => exercises.reduce((total, e) => total + e.minutes, 0)

export function render(): string {
  const exercises: Exercise[] = content('exercises.json')
  const total = sum(exercises)
  const tracks = (content('take-home/tracks.json') as Track[]).map((t) => {
    const list: Exercise[] = content(`take-home/${t.id}/exercises.json`)
    const status = t.published ? '' : ' Not published yet: students cannot see it.'
    return `### ${t.title}

Page: \`/take-home/${t.id}\`. Quiz: \`/take-home/${t.id}/quiz\`.${status}

${table(list)}

${list.length} exercises, ${sum(list)} minutes, plus the track's quiz.`
  })

  return `# Exercise ids

<!-- Generated by \`bun scripts/exercise-ids.ts\` from apps/api/resources/content. Do not edit by hand. -->

Each exercise has a stable id. It appears in the exercise's URL (\`/exercises/<id>\`), is how
completions are stored, and picks the exercise for the Live page's focused view.

## The workshop

${table(exercises)}

${exercises.length} exercises, ${total} minutes, plus the quiz.

## Take-home tracks

Self-paced, for after the workshop. Each track has its own quiz, and neither counts in the
Live page's workshop figures. Take-home ids start with the track's id, and are unique across
every track.

${tracks.join('\n\n')}

The same lists, as JSON, from a running Dojo: \`GET /api/exercises\` (for example
http://localhost:8000/api/exercises). Each entry has \`number\`, \`id\`, \`title\`, \`minutes\`,
\`page\` and \`live\` (relative paths), and \`totalMinutes\` sums the workshop's. Published
take-home tracks are under \`takeHome\`, each with its own \`exercises\`.

## Using an id on the Live page

- \`/live?embed&exercise=<id>\` shows that exercise with one on each side, highlighted.
- Add \`&count=5\` (any number) to show more. At the start or end of the course the
  window shifts in, so the count stays the same.
- Leave out \`embed\` to keep the header and the quiz section.
- For an iframe whose exercise changes (a slide deck), put the settings after a \`#\`:
  \`/live?embed#exercise=<id>&count=5\`. Changing only the part after the \`#\` moves the list
  along without reloading the frame. \`embed\` stays before the \`#\`.
- A take-home id shows that track's list instead, numbered within the track.
- An id that doesn't exist shows every exercise, with a note saying so.

For example, on a local stack: http://localhost:8000/live?embed&exercise=${exercises[Math.min(6, exercises.length - 1)].id}
`
}

if (import.meta.main) {
  writeFileSync(DOC, render())
  console.log(`Wrote ${DOC}`)
}
