// Writes docs/exercise-ids.md from apps/api/resources/content/exercises.json.
// Run after any change to the exercises: bun scripts/exercise-ids.ts
// (tests/docs.test.ts fails while the doc is out of date).
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
export const DOC = join(root, 'docs/exercise-ids.md')

type Exercise = { id: string; title: string; minutes: number }

export function render(): string {
  const exercises: Exercise[] = JSON.parse(readFileSync(join(root, 'apps/api/resources/content/exercises.json'), 'utf8'))
  const rows = exercises.map((e, i) => `| ${i + 1} | \`${e.id}\` | ${e.title.replace(/\|/g, '\\|')} | ${e.minutes} | \`/live?embed&exercise=${e.id}\` |`)
  const total = exercises.reduce((sum, e) => sum + e.minutes, 0)

  return `# Exercise ids

<!-- Generated by \`bun scripts/exercise-ids.ts\` from apps/api/resources/content/exercises.json. Do not edit by hand. -->

Each exercise has a stable id. It appears in the exercise's URL (\`/exercises/<id>\`), is how
completions are stored, and picks the exercise for the Live page's focused view.

| # | Id | Title | Minutes | Live page, focused on it |
|---|---|---|---|---|
${rows.join('\n')}

${exercises.length} exercises, ${total} minutes, plus the quiz.

The same list, as JSON, from a running Dojo: \`GET /api/exercises\` (for example
http://localhost:8000/api/exercises). Each entry has \`number\`, \`id\`, \`title\`, \`minutes\`,
\`page\` and \`live\` (relative paths), and \`totalMinutes\` sums them.

## Using an id on the Live page

- \`/live?embed&exercise=<id>\` shows that exercise with one on each side, highlighted.
- Add \`&count=5\` (any number) to show more. At the start or end of the course the
  window shifts in, so the count stays the same.
- Leave out \`embed\` to keep the header and the quiz section.
- An id that doesn't exist shows every exercise, with a note saying so.

For example, on a local stack: http://localhost:8000/live?embed&exercise=${exercises[Math.min(6, exercises.length - 1)].id}
`
}

if (import.meta.main) {
  writeFileSync(DOC, render())
  console.log(`Wrote ${DOC}`)
}
